# Generated by Django 4.2.25 on 2025-10-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('DELIVERYOUT', 'outfordelivery'), ('DELIVERED', 'deliverySuccess')], default='PENDING', max_length=20),
        ),
    ]
