# Generated by Django 4.2.25 on 2025-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_sizes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('CHICKEN', 'Chicken'), ('VEG', 'Veg')], default='VEG', max_length=50),
        ),
    ]
