# Generated by Django 4.2.25 on 2025-10-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_menuitem_available_sizes_menuitem_size_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='size_prices',
        ),
    ]
