# Generated by Django 4.2.25 on 2025-10-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
