# Generated by Django 4.2.25 on 2025-10-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_data',
            field=models.JSONField(default=list),
        ),
    ]
