# Generated by Django 4.2.25 on 2025-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_items_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('CHICKEN', 'Chicken'), ('VEG', 'Veg'), ('DRINKS', 'Drinks')], default='VEG', max_length=50),
        ),
    ]
