# Generated by Django 4.2.25 on 2025-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_customuser_otp_customuser_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
