# Generated by Django 4.2.25 on 2025-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Status',
                'verbose_name_plural': 'Delivery Status',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('DELIVERYOUT', 'Out_for_delivery'), ('DELIVERED', 'Delivery_Success'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
