# Generated by Django 4.2.25 on 2025-12-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_customuser_otp_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
